-- 코드를 입력하세요
SELECT P.PRODUCT_CODE AS PRODUCT_CODE, (O.CNT * P.PRICE)AS SALES
FROM PRODUCT P
RIGHT JOIN (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS CNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) O
ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC